// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchCreateBoardCodes(arg1) {
  return window['go']['main']['App']['BatchCreateBoardCodes'](arg1);
}

export function BatchCreateCPUCodes(arg1) {
  return window['go']['main']['App']['BatchCreateCPUCodes'](arg1);
}

export function ListBoardCodes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListBoardCodes'](arg1, arg2, arg3);
}

export function ListCPUCodes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListCPUCodes'](arg1, arg2, arg3);
}
