// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BatchCreateBoardCodes(arg1:main.BatchCreateBoardCode):Promise<void>;

export function BatchCreateCPUCodes(arg1:main.BatchCreateCPUCode):Promise<void>;

export function ListBoardCodes(arg1:number,arg2:number,arg3:main.BoardCodeFilter):Promise<main.ListResponse>;

export function ListCPUCodes(arg1:number,arg2:number,arg3:main.CPUCodeFilter):Promise<main.ListResponse>;
